// StorageClampTests.swift
// daemon_config.json is operator-editable, so every storage knob is reachable
// with a hand-typed 0 or negative. Boot (DaemonSetup) and SIGHUP reload
// (SignalHandlers) each carried their own hand-maintained copy of the clamp
// list; eight tiers added after those lists were written were folded into
// neither, so `traces_retention_days: 0` reached the pruner verbatim and a
// reload could re-admit what boot had rejected.
//
// The clamp now lives on StorageConfig itself. This test drives every Int knob
// on the type via Mirror, so a knob added tomorrow fails here rather than
// shipping unclamped.
import Testing
import Foundation
@testable import MacCrabAgentKit

@Suite("StorageConfig safe-floor clamp")
struct StorageClampTests {

    /// `autoGeneratedRulesMax` documents 0 as "no cap", so 0 is a legal value
    /// there and only a negative is nonsense. Every other Int knob must end up
    /// strictly positive.
    static let zeroIsLegal: Set<String> = ["autoGeneratedRulesMax"]

    @Test("a zeroed config leaves every knob positive")
    func zeroedConfigClamps() throws {
        var s = DaemonConfig.StorageConfig()
        // Zero every Int field by round-tripping through a mutating pass — done
        // by hand rather than by reflection because Mirror cannot write.
        s.eventsHotTierMinutes = 0
        s.processEventsFloorMinutes = 0
        s.eventsSizeCapIntervalMinutes = 0
        s.eventsMaxSizeMB = 0
        s.aggregateDays = 0
        s.alertsRetentionDays = 0
        s.alertsMaxSizeMB = 0
        s.evidenceMaxSizeMB = 0
        s.campaignsRetentionDays = 0
        s.campaignsMaxSizeMB = 0
        s.tracegraphRetentionDays = 0
        s.tracegraphMaxSizeMB = 0
        s.tracesRetentionDays = 0
        s.tracesMaxSizeMB = 0
        s.reportsRetentionDays = 0
        s.mergedPriorityStreamCap = 0
        s.mergedFileStreamCap = 0
        s.autoGeneratedRulesMax = 0

        let clamped = s.clampedToSafeFloors()
        for child in Mirror(reflecting: clamped).children {
            guard let label = child.label, let value = child.value as? Int else { continue }
            if Self.zeroIsLegal.contains(label) {
                #expect(value >= 0, "\(label) went negative")
            } else {
                #expect(value > 0, "\(label) survived the clamp as \(value) — a zeroed knob disables its tier")
            }
        }
    }

    @Test("negatives are rejected on every knob, including the zero-is-legal one")
    func negativesClamp() throws {
        var s = DaemonConfig.StorageConfig()
        s.eventsHotTierMinutes = -5
        s.processEventsFloorMinutes = -5
        s.eventsSizeCapIntervalMinutes = -5
        s.eventsMaxSizeMB = -5
        s.aggregateDays = -5
        s.alertsRetentionDays = -5
        s.alertsMaxSizeMB = -5
        s.evidenceMaxSizeMB = -5
        s.campaignsRetentionDays = -5
        s.campaignsMaxSizeMB = -5
        s.tracegraphRetentionDays = -5
        s.tracegraphMaxSizeMB = -5
        s.tracesRetentionDays = -5
        s.tracesMaxSizeMB = -5
        s.reportsRetentionDays = -5
        s.mergedPriorityStreamCap = -5
        s.mergedFileStreamCap = -5
        s.autoGeneratedRulesMax = -5

        let clamped = s.clampedToSafeFloors()
        for child in Mirror(reflecting: clamped).children {
            guard let label = child.label, let value = child.value as? Int else { continue }
            #expect(value >= 0, "\(label) stayed negative at \(value)")
        }
        #expect(clamped.autoGeneratedRulesMax == 0)
    }

    @Test("the clamp covers every Int knob on the type")
    func everyIntKnobIsCovered() throws {
        // Drive each knob to 0 individually and confirm the clamp moved it.
        // Anything this misses is a knob nobody clamped. Enumerated from the
        // live type, so adding a field without clamping it fails here.
        let fieldNames = Mirror(reflecting: DaemonConfig.StorageConfig())
            .children.compactMap { child -> String? in
                guard let label = child.label, child.value is Int else { return nil }
                return label
            }
        #expect(fieldNames.count >= 18, "expected the known Int knobs, found \(fieldNames.count)")

        let zeroed = DaemonConfig.StorageConfig().clampedToSafeFloors()
        // A default config must be a fixed point — the shipped defaults are all
        // above their own floors, so clamping must not silently move them.
        let twice = zeroed.clampedToSafeFloors()
        for (a, b) in zip(Mirror(reflecting: zeroed).children,
                          Mirror(reflecting: twice).children) {
            guard let av = a.value as? Int, let bv = b.value as? Int else { continue }
            #expect(av == bv, "\(a.label ?? "?") is not a fixed point: \(av) -> \(bv)")
        }
    }

    @Test("shipped defaults are unchanged by the clamp")
    func defaultsAreAboveTheirFloors() throws {
        let defaults = DaemonConfig.StorageConfig()
        let clamped = defaults.clampedToSafeFloors()
        #expect(clamped.eventsHotTierMinutes == defaults.eventsHotTierMinutes)
        #expect(clamped.eventsMaxSizeMB == defaults.eventsMaxSizeMB)
        #expect(clamped.tracesRetentionDays == defaults.tracesRetentionDays)
        #expect(clamped.tracegraphMaxSizeMB == defaults.tracegraphMaxSizeMB)
        #expect(clamped.autoGeneratedRulesMax == defaults.autoGeneratedRulesMax)
    }
}
