// Alert.swift
// MacCrabCore
//
// A detection alert produced when an event matches a detection rule.

import Foundation

// MARK: - Alert

/// Represents a detection alert generated by the rule engine.
///
/// Each alert ties back to the originating `Event` via `eventId` and
/// records which rule fired, the assessed severity, and any MITRE ATT&CK
/// mappings defined in the rule.
public struct Alert: Codable, Sendable, Hashable, Identifiable {

    /// Unique alert identifier (UUID string).
    public let id: String

    /// When the alert was generated.
    public let timestamp: Date

    /// Identifier of the detection rule that fired.
    public let ruleId: String

    /// Human-readable title of the detection rule.
    public let ruleTitle: String

    /// Severity level of the alert.
    public let severity: Severity

    /// The event that triggered this alert.
    public let eventId: String

    /// Path to the process that triggered the alert.
    public let processPath: String?

    /// Name of the process that triggered the alert.
    public let processName: String?

    /// Free-text description of the alert.
    public let description: String?

    /// Comma-separated MITRE ATT&CK tactic identifiers (e.g. `"TA0003,TA0005"`).
    public let mitreTactics: String?

    /// Comma-separated MITRE ATT&CK technique identifiers (e.g. `"T1059.004,T1547.001"`).
    public let mitreTechniques: String?

    /// Whether this alert has been suppressed (de-duplicated / silenced).
    public var suppressed: Bool

    // MARK: Initializer

    public init(
        id: String = UUID().uuidString,
        timestamp: Date = Date(),
        ruleId: String,
        ruleTitle: String,
        severity: Severity,
        eventId: String,
        processPath: String? = nil,
        processName: String? = nil,
        description: String? = nil,
        mitreTactics: String? = nil,
        mitreTechniques: String? = nil,
        suppressed: Bool = false
    ) {
        self.id = id
        self.timestamp = timestamp
        self.ruleId = ruleId
        self.ruleTitle = ruleTitle
        self.severity = severity
        self.eventId = eventId
        self.processPath = processPath
        self.processName = processName
        self.description = description
        self.mitreTactics = mitreTactics
        self.mitreTechniques = mitreTechniques
        self.suppressed = suppressed
    }
}
