// RuleGenerator.swift
// MacCrabCore
//
// Generates Sigma-compatible YAML detection rules from observed attack patterns.
// When a campaign or kill chain is detected, this engine extracts the key
// indicators and produces a rule that would catch similar attacks in the future.

import Foundation
import os.log

/// Generates Sigma-compatible YAML detection rules from observed attack patterns.
/// When a campaign or kill chain is detected, this engine extracts the key
/// indicators and produces a rule that would catch similar attacks in the future.
public actor RuleGenerator {
    private let logger = Logger(subsystem: "com.maccrab.detection", category: "rule-generator")

    /// A generated rule ready to be written to disk.
    public struct GeneratedRule: Sendable {
        public let yaml: String
        public let filename: String
        public let title: String
        public let description: String
        public let severity: String
        public let generatedAt: Date
    }

    private let outputDir: String
    private var generatedCount: Int = 0

    public init(outputDir: String) {
        self.outputDir = outputDir
    }

    /// Generate a rule from a campaign detection.
    /// Returns the generated rule, or nil if the campaign lacks enough signal.
    public func generateFromCampaign(
        campaignType: String,
        alerts: [(ruleId: String, ruleTitle: String, processPath: String?, tactics: Set<String>, timestamp: Date)]
    ) -> GeneratedRule? {
        guard alerts.count >= 2 else { return nil }

        generatedCount += 1
        let ruleId = "d1a2b3c4-auto-\(String(format: "%04d", generatedCount))-\(UUID().uuidString.prefix(4))"
        let timestamp = ISO8601DateFormatter().string(from: Date()).prefix(10)

        // Extract common indicators from the alerts
        let processes = Set(alerts.compactMap { $0.processPath })
        let tactics = alerts.reduce(into: Set<String>()) { $0.formUnion($1.tactics) }
        let ruleNames = alerts.map { $0.ruleTitle }

        // Build the detection based on what we observed
        let title = "Auto-Generated: \(campaignType.replacingOccurrences(of: "_", with: " ").capitalized) Pattern"

        var yaml = """
        title: \(title)
        id: \(ruleId)
        status: experimental
        description: >
            Automatically generated from observed \(campaignType) campaign.
            Original alerts: \(ruleNames.joined(separator: "; ")).
            Generated by MacCrab RuleGenerator on \(timestamp).
        author: MacCrab Auto-Generator
        date: \(timestamp)
        tags:

        """

        for tactic in tactics.sorted() {
            yaml += "    - \(tactic)\n"
        }

        // Generate detection based on observed process paths
        if !processes.isEmpty {
            yaml += """
            logsource:
                category: process_creation
                product: macos
            detection:
                selection:
                    Image|endswith:

            """
            for proc in processes.prefix(5) {
                let basename = "/" + (proc as NSString).lastPathComponent
                yaml += "            - '\(basename)'\n"
            }
            yaml += """
                filter_system:
                    ParentImage|startswith:
                        - '/System/'
                        - '/usr/libexec/'
                        - '/usr/sbin/'
                filter_apple_signed:
                    SignerType: 'apple'
                condition: selection and not filter_system and not filter_apple_signed

            """
        } else {
            yaml += """
            logsource:
                category: process_creation
                product: macos
            detection:
                selection:
                    CommandLine|contains: 'placeholder'
                condition: selection

            """
        }

        yaml += """
        falsepositives:
            - Legitimate use of the same tools
            - Auto-generated rule may have high false positive rate — review and tune
        level: high
        """

        let filename = "auto_\(campaignType)_\(generatedCount).yml"

        let rule = GeneratedRule(
            yaml: yaml,
            filename: filename,
            title: title,
            description: "Generated from \(campaignType) campaign with \(alerts.count) contributing alerts",
            severity: "high",
            generatedAt: Date()
        )

        // Write to disk
        writeRule(rule)

        logger.info("Generated rule: \(title) → \(filename)")
        return rule
    }

    /// Write a generated rule to the output directory.
    private func writeRule(_ rule: GeneratedRule) {
        let fm = FileManager.default
        let autoDir = outputDir + "/auto_generated"
        try? fm.createDirectory(atPath: autoDir, withIntermediateDirectories: true)
        let path = autoDir + "/" + rule.filename
        try? rule.yaml.write(toFile: path, atomically: true, encoding: .utf8)
    }

    /// Get count of generated rules.
    public func stats() -> Int { generatedCount }
}
